name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Run tests
      run: |
        npm test
        
    - name: Start server
      run: |
        npm install -g serve
        serve -s . -p 3000 &
        
    - name: Wait for server
      run: |
        sleep 5
        
    - name: Check if files exist
      run: |
        test -f index.html
        test -f style.css
        test -f game.js
        test -f sw.js
        test -f manifest.json
        test -f README.md
        test -f LICENSE 